services:
  - type: web
    name: goodup
    runtime: python
    plan: free
    buildCommand: "true"
    startCommand: "python3 server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
